depends_on: [ test ]

steps:
  - name: build container image
    when:
      - event: push
      - event: cron
      - event: manual
    image: docker.io/nixos/nix
    environment:
      FORGEJO_PACKAGES_ACCESS:
        from_secret: FORGEJO_PACKAGES_ACCESS
      GITHUB_PACKAGES_ACCESS:
        from_secret: GITHUB_PACKAGES_ACCESS
    privileged: true
    commands:
      - nix --extra-experimental-features "nix-command flakes" build -o container.tar.gz.lnk ".#pixeldike-oci"
      - cp $(realpath container.tar.gz.lnk) container.tar.gz

  - name: publish container image
    when:
      - event: manual
        branch: main
      - event: push
        branch: main
      - event: cron
        cron: periodic-rebuild
    image: quay.io/containers/skopeo
    environment:
      FORGEJO_PACKAGES_ACCESS:
        from_secret: FORGEJO_PACKAGES_ACCESS
      GITHUB_PACKAGES_ACCESS:
        from_secret: GITHUB_PACKAGES_ACCESS
    commands:
      - skopeo copy --dest-username lilly --dest-password $FORGEJO_PACKAGES_ACCESS docker-archive:container.tar.gz docker://git.lly.sh/lilly/pixeldike
      - skopeo copy --dest-username lilioid --dest-password $GITHUB_PACKAGES_ACCESS docker-archive:container.tar.gz docker://ghcr.io/lilioid/pixeldike
